
var weatherIcon = {
    '': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/none.png",
	'晴': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/q.png",
    '多云': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/qzdy.png",
    '阴': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/yt.png",
    '阵雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/zy.png",
    '雷阵雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/lzy.png",
    '雷阵雨并伴有冰雹': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/lzx.png",
    '雨夹雪': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/yjx.png",
    '小雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/xy.png",
    '中雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/zy.png",
    '大雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/dayu.png",
    '暴雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/dabaoyu.png",
    '大暴雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/dabaoyu.png",
    '特大暴雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/tedabaoyu.png",
    '阵雪': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/bx.png",
    '小雪': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/xiaoxue.png",
    '中雪': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/zx.png",
    '大雪': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/daxue.png",
    '暴雪': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/baoxue.png",
    '雾': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/wu.png",
    '冻雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/dongyu.png",
    '沙尘暴': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/shachengbao.png",
    '小雨-中雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/zy.png",
    '中雨-大雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/dayu.png",
    '大雨-暴雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/by.png",
    '暴雨-大暴雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/by.png",
    '大暴雨-特大暴雨': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/tdzy.png",
    '小雪-中雪': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/zx.png",
    '中雪-大雪': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/daxue.png",
    '大雪-暴雪': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/baoxue.png",
    '浮尘': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/fucheng.png",
    '扬沙': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/ys.png",
    '强沙尘暴': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/qiangshachengbao.png",
    '飑': "",
    '龙卷风': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/longjunfeng.png",
    '弱高吹雪': "",
    '轻雾': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/qingwu.png",
    '霾': "https://tcb-static-img.oss-cn-shenzhen.aliyuncs.com/wm.png"
};


module.exports = weatherIcon;